### ISSUE TITLE
MALWARE + DUALHOOK

### ISSUE THREAD

**Issue by THEKILERFRIEND** [Hawkish-Team/Hawkish-Grabber#1]
THE DEVELOPER OF THIS TOOL IS KNOWN FOR DUALHOOKING AND EVEN HACKING YOUR ACCOUNTS! DO NOT USE THIS UNLESS YOU WANT TO GET YOUR SHIT LEAKED

**Comment by Hawkishx** [comment]
we don't have any url in the github version so...
what dualhook? we don't have any api, any extern url, any access

**Comment by Hawkishx** [comment]
please be a good boy and sht up.
