### ISSUE TITLE
error after build

### ISSUE THREAD

**Issue by nolan70gaming** [Hawkish-Team/Hawkish-Grabber#10]
when I try to open it I have all time the same error: https://imgur.com/a/HOboSvG

I try with Python 11 and 10 but same.

**Comment by nolan70gaming** [comment]
I try now and always same problem

**Comment by Hawkishx** [comment]
okay new update try it

**Comment by nolan70gaming** [comment]
Now I got this https://imgur.com/a/gcVr4Q9

**Comment by Hawkishx** [comment]
patched

**Comment by nolan70gaming** [comment]
Finaly works perfectly ! Thanks for update !
