### ISSUE TITLE
stupid github user #2

### ISSUE THREAD

**Issue by Pasha-malware** [Hawkish-Team/Hawkish-Grabber#2]
Dualhooked bs, known for dualhooking I even got screen shots admitting that he did so
![Screenshot 2023-05-29 203453](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/116023651/ba20abe7-8e23-45d1-835d-7db5a0fa7ed8)
![Screenshot 2023-05-29 221733](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/116023651/63b65e36-5fba-420a-84fb-518e646900fd)

**Comment by Hawkishx** [comment]
dualhook with what link? :ppp
