### ISSUE TITLE
just a dumb guy #2

### ISSUE THREAD

**Issue by live-industrial** [Hawkish-Team/Hawkish-Grabber#5]

**Comment by Hawkishx** [comment]
![image](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/132696065/b8c5a9b3-f089-418c-b08f-24cc3dcbad8e)
camera screenshot 🤡

**Comment by Hawkishx** [comment]
![image](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/132696065/614b3957-c8c9-4691-b510-603b9d65d66a)
*
