### ISSUE TITLE
Organize the cookies

### ISSUE THREAD

**Issue by Lol12343473** [Hawkish-Team/Hawkish-Grabber#7]
Can you make them actually usable or am i just dumb

**Comment by Hawkishx** [comment]
i format all cookies for the extension "cookie quick manager" on mozilla you can import all cookies easily

**Comment by Hawkishx** [comment]
![image](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/132696065/b8b72315-d61a-4f6c-9227-6b4eacc2e40f)
![image](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/132696065/4026e333-8ec4-46c3-a781-d819c761fb70)

**Comment by Lol12343473** [comment]
Okay thanks

**Comment by Lol12343473** [comment]
But how do I sue the cookies once they are exported

**Comment by Lol12343473** [comment]
use*

**Comment by Hawkishx** [comment]
go on website like gmail.com
