### ISSUE TITLE
cannot install pyperclip

### ISSUE THREAD

**Issue by ggauzin** [Hawkish-Team/Hawkish-Grabber#8]
![image](https://github.com/Hawkish-Team/Hawkish-Grabber/assets/128216038/e0457b0c-193c-4d9e-bc7d-30e3693c04f3)

**Comment by Hawkishx** [comment]
try to install it in admin

**Comment by ggauzin** [comment]
no, the same error

**Comment by Hawkishx** [comment]
https://www.partitionwizard.com/partitionmanager/python-setup-py-egg-info-failed-with-error-code-1.html
